CXX := g++
CXXFLAGS := -std=c++20 -Wall -Wextra -O2 \
           -MMD -MP \
           -Iinclude

# Linker flags - default: OpenSSL crypto + zlib
LDFLAGS := -lcrypto -lz

# Target name
TARGET := GitWork

# Sources (adjust if needed)
SRCS := $(wildcard src/*.cpp) main.cpp

# Object files (placed next to each .cpp)
OBJS := $(SRCS:.cpp=.o)

# Dependency files (auto-generated by -MMD)
DEPS := $(OBJS:.o=.d)

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(LDFLAGS)

# Compile .cpp -> .o, auto-generate .d files (via -MMD)
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Include dependency files; ignore missing ones
-include $(DEPS)

clean:
	rm -f $(TARGET) $(OBJS) $(DEPS)
